version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.15.6
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment: 
      TEST_RESULTS: /tmp/test-results
      PROJECT_NAME: minimal-service
      VERSION: 1.0.0
      GOFILES: $(wildcard *./.go)
    steps:
      - checkout
      - run: 
          name: Create dir 
          command: mkdir -p $TEST_RESULTS
      - run:
          name: Run go get
          command: go get -v -t -d ./...
      - run:
          name: Run go test
          command: go test -v ./handlers/
      - run: 
          name: Build
          command: go build -o $(TEST_RESULTS)/bin/$(PROJECT_NAME) $(GOFILES)
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Start service
          command: $(TEST_RESULTS)/bin/minimal-service
      - run:
          name: Check health
          command: curl -s http://localhost:9090/health

      - store_artifacts: 
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
